### ISSUE TITLE
Input isn't working on win11

### ISSUE THREAD

**Issue by nejroseld** [mokeyish/obsidian-code-emitter#67]
**Issue description:**
I run the python code with input() on android obsisdian app and it works, but on my windows11 PC I can't execute this code

**Video Android:**
https://github.com/user-attachments/assets/1c1c8102-67f4-4580-9857-0f3f13698381

**Video Windows 11:**
https://github.com/user-attachments/assets/9ad4561c-d4d5-49ae-a626-3f8012042255

**Error text:**
```
PythonError: Traceback (most recent call last):
File "/lib/python3.10/asyncio/futures.py", line 201, in result
raise self._exception
File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
result = coro.send(None)
File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
await CodeRunner(
File "/lib/python3.10/site-packages/_pyodide/_base.py", line 357, in run_async
coroutine = eval(self.code, globals, locals)
File "", line 1, in
OSError: [Errno 29] I/O error
```

**Comment by Hannes-Schniz** [comment]
Same issue persists in the Linux install.

**Error message:**
PythonError: Traceback (most recent call last):
File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
await CodeRunner(
File "/lib/python312.zip/_pyodide/_base.py", line 410, in run_async
coroutine = eval(self.code, globals, locals)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<exec>", line 1, in <module>
OSError: [Errno 29] I/O error

If there is a workaround or a fix that would be appreciated since its a little annoying :)

**Comment by mokeyish** [comment]
Input is not currently supported and needs to be developed and adapted. The following is a reference document. Those who are capable can add this feature.

https://pyodide.org/en/stable/usage/streams.html#a-stdin-handler
